### ISSUE TITLE
exceptions.html_error_template render fail in python3

### ISSUE THREAD

**Issue by hilarryxu** [sqlalchemy/mako#293] opened 2019-04-30 08:53 UTC
When use exceptions.html_error_template in python3, got:

```python
    File "python3.7/site-packages/mako/runtime.py", line 899, in _exec_template
        callable_(context, *args, **kwargs)
    File "memory:0x7efcac2aa908", line 49, in render_body
    TypeError: a bytes-like object is required, not 'str'
```

caused by 
```python
    tback = RichTraceback(error=error, traceback=traceback)
    src = tback.source
    line = tback.lineno
    if src:
        lines = src.split('\n')
```

here `tback.source` is bytes in python3, so `src.split` raise TypeError

**Comment by zzzeek** [comment] 2019-04-30 14:06
hi there -

can you please provide a complete MCVE test case?  I'm not able to reproduce, although Im not sure it's working correctly nonetheless:

```

from mako.template import Template
from mako import exceptions

try:
    t = Template("<% print(x) %>")
    print(t.render())
except:
    print(exceptions.html_error_template().render())
```

I get back HTML source as bytes.  however if I call render_unicode(), I get good HTML.   No stack trace in either case.   Using Python 3.7.0.

**Comment by hilarryxu** [comment] 2019-05-06 06:50
Like this when use `TemplateLookup`

```python
from mako.lookup import TemplateLookup
from mako.exceptions import MakoException, html_error_template

try:
    template_lookup = TemplateLookup()
    tpl = template_lookup.get_template('not_found.html')
    tpl.render()
except MakoException:
    print(html_error_template().render())
```

Using Python 3.7.1 Mako 1.0.9

**Comment by sqla-tester** [comment] 2019-05-10 03:08
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Use utf-8 encoding for traceback source with no encoding in py3k** https://gerrit.sqlalchemy.org/1261

**Comment by hilarryxu** [comment] 2019-05-10 09:50
It works, thank you.

**Closed as completed** 2019-05-10 14:03 UTC
Labels: bug
